# **Applying Recursive_Sorting_Algorithm using Mesh 2D**

In [10]:
import numpy as np

def sort_quadrant(matrix):
    """
    Sort a quadrant in snakelike order.
    """
    rows, cols = matrix.shape
    for i in range(rows):
        matrix[i, :] = np.sort(matrix[i, :]) if i % 2 == 0 else np.sort(matrix[i, :])[::-1]
    return matrix

def odd_even_transposition_sort(arr):
    """
    Sort a linear array using odd-even transposition sort.
    """
    n = len(arr)
    for _ in range(n):
        for i in range(1, n, 2):  # Odd phase
            if i < n - 1 and arr[i] > arr[i + 1]:
                arr[i], arr[i + 1] = arr[i + 1], arr[i]
        for i in range(0, n - 1, 2):  # Even phase
            if arr[i] > arr[i + 1]:
                arr[i], arr[i + 1] = arr[i + 1], arr[i]
    return arr

def recursive_sort_2d_mesh(matrix):
    """
    Implements the First Recursive Sorting Algorithm on a 2D Mesh.
    """
    n, m = matrix.shape
    assert n == m, "Matrix must be square"

    # Step 1: Divide into four quadrants and sort them in snakelike order
    mid = n // 2
    print("Step 1: Sorting quadrants in snakelike order")
    if mid > 0:
        matrix[:mid, :mid] = sort_quadrant(matrix[:mid, :mid])  # Top-left quadrant
        print("Top-left quadrant sorted:\n", matrix[:mid, :mid])
        matrix[:mid, mid:] = sort_quadrant(matrix[:mid, mid:])  # Top-right quadrant
        print("Top-right quadrant sorted:\n", matrix[:mid, mid:])
        matrix[mid:, :mid] = sort_quadrant(matrix[mid:, :mid])  # Bottom-left quadrant
        print("Bottom-left quadrant sorted:\n", matrix[mid:, :mid])
        matrix[mid:, mid:] = sort_quadrant(matrix[mid:, mid:])  # Bottom-right quadrant
        print("Bottom-right quadrant sorted:\n", matrix[mid:, mid:])

    # Step 2: Sort rows in snakelike order
    print("\nStep 2: Sorting rows in snakelike order")
    for i in range(n):
        matrix[i, :] = np.sort(matrix[i, :]) if i % 2 == 0 else np.sort(matrix[i, :])[::-1]
        print(f"Row {i} sorted:\n", matrix[i, :])

    # Step 3: Sort columns top to bottom
    print("\nStep 3: Sorting columns top to bottom")
    for j in range(n):
        matrix[:, j] = np.sort(matrix[:, j])
        print(f"Column {j} sorted:\n", matrix[:, j])

    # Step 4: Apply odd-even transposition sort to the flattened matrix
    print("\nStep 4: Applying odd-even transposition sort")
    linear_array = matrix.flatten()
    print("Flattened array before sorting:\n", linear_array)
    linear_array = odd_even_transposition_sort(linear_array)
    print("Flattened array after sorting:\n", linear_array)

    # Reshape back into a 2D matrix
    sorted_matrix = linear_array.reshape((n, n))
    print("\nFinal sorted matrix:\n", sorted_matrix)

    return sorted_matrix

# Example Usage
if __name__ == "__main__":
    # Input: N x N matrix (can be any size)
    size = int(input("Enter the size of the square matrix (N): "))
    matrix = np.random.randint(1, 100, (size, size))  # Generate a random N x N matrix

    print("Original Matrix:")
    print(matrix)

    sorted_matrix = recursive_sort_2d_mesh(matrix)

    print("\nSorted Matrix:")
    print(sorted_matrix)

Enter the size of the square matrix (N): 4
Original Matrix:
[[21 86 86 90]
 [98 18 83 37]
 [ 4 81 28 76]
 [27 93 72 73]]
Step 1: Sorting quadrants in snakelike order
Top-left quadrant sorted:
 [[21 86]
 [98 18]]
Top-right quadrant sorted:
 [[86 90]
 [83 37]]
Bottom-left quadrant sorted:
 [[ 4 81]
 [93 27]]
Bottom-right quadrant sorted:
 [[28 76]
 [73 72]]

Step 2: Sorting rows in snakelike order
Row 0 sorted:
 [21 86 86 90]
Row 1 sorted:
 [98 83 37 18]
Row 2 sorted:
 [ 4 28 76 81]
Row 3 sorted:
 [93 73 72 27]

Step 3: Sorting columns top to bottom
Column 0 sorted:
 [ 4 21 93 98]
Column 1 sorted:
 [28 73 83 86]
Column 2 sorted:
 [37 72 76 86]
Column 3 sorted:
 [18 27 81 90]

Step 4: Applying odd-even transposition sort
Flattened array before sorting:
 [ 4 28 37 18 21 73 72 27 93 83 76 81 98 86 86 90]
Flattened array after sorting:
 [ 4 18 21 27 28 37 72 73 76 81 83 86 86 90 93 98]

Final sorted matrix:
 [[ 4 18 21 27]
 [28 37 72 73]
 [76 81 83 86]
 [86 90 93 98]]

Sorted Matrix:
[[ 4 18